microsoft/PowerApps-Samples

cds/orgsvc/C#/FollowupPlugin/FollowupPlugin.sln
cds/orgsvc/C#/FollowupPlugin/FollowupPlugin/FollowupPlugin.csproj
cds/orgsvc/C#/FollowupPlugin/FollowupPlugin/Properties/AssemblyInfo.cs
cds/orgsvc/C#/FollowupPlugin/FollowupPlugin/SampleProgram.cs
cds/orgsvc/C#/FollowupPlugin/FollowupPlugin/packages.config
cds/orgsvc/C#/FollowupPlugin/README.md

This sample was mentioned in the "Write and register a plug-in" tutorial but was missing in the sample download repository.

New powerapps sample for a simple plug-in

---

cds/orgsvc/C#/FollowupPlugin/README.md
cds/orgsvc/C#/WebAccessPlugin/README.md

More detailed README info for the web access plug-in and follow-up plug-in

Added more detailed README information

---

ai-builder/README.md

Updating read me section because people are trying to download and upload CSV files when importing data. This is not necessary and you only need to copy the raw link of the CSV files.

Add note that download csv is not needed for import

---

cds/orgsvc/C#/DiscoveryService/DiscoveryService.csproj
cds/orgsvc/C#/DiscoveryService/README.md
cds/orgsvc/C#/DiscoveryService/SampleMethods.cs
cds/orgsvc/C#/DiscoveryService/SampleProgram.cs
cds/orgsvc/C#/DiscoveryService/packages.config

Updating Regional Discovery Service Sample to use Token based auth.

Update Sample for Discovery

---

cds/webapi/C#/GlobalDiscovery/GlobalDiscovery/GlobalDiscovery.csproj
cds/webapi/C#/GlobalDiscovery/GlobalDiscovery/Program.cs

Remove FQN for referenced assemblies to allow Nuget Version updates.
Added Missing referance to System.configuration.

Updating GDS Sample for streamlined auth and resource lookup.

---

cds/webapi/C#/CDSWebApiService/App.config
cds/webapi/C#/CDSWebApiService/AsyncParallelOperations/AsyncParallelOperations.csproj
cds/webapi/C#/CDSWebApiService/AsyncParallelOperations/Program.cs
cds/webapi/C#/CDSWebApiService/AsyncParallelOperations/Properties/AssemblyInfo.cs
cds/webapi/C#/CDSWebApiService/AsyncParallelOperations/README.md
cds/webapi/C#/CDSWebApiService/AsyncParallelOperations/packages.config
cds/webapi/C#/CDSWebApiService/BasicOperations/BasicOperations.csproj
cds/webapi/C#/CDSWebApiService/BasicOperations/Program.cs
cds/webapi/C#/CDSWebApiService/BasicOperations/Properties/AssemblyInfo.cs
cds/webapi/C#/CDSWebApiService/BasicOperations/README.md
cds/webapi/C#/CDSWebApiService/BasicOperations/packages.config
cds/webapi/C#/CDSWebApiService/CDSWebApiService.sln
cds/webapi/C#/CDSWebApiService/CDSWebApiService/CDSWebApiService.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService/CDSWebApiService.csproj
cds/webapi/C#/CDSWebApiService/CDSWebApiService/Extensions.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService/OAuthMessageHandler.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService/Properties/AssemblyInfo.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService/README.md
cds/webapi/C#/CDSWebApiService/CDSWebApiService/ServiceConfig.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService/ServiceException.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService/packages.config
cds/webapi/C#/CDSWebApiService/ParallelOperations/ParallelOperations.csproj
cds/webapi/C#/CDSWebApiService/ParallelOperations/Program.cs
cds/webapi/C#/CDSWebApiService/ParallelOperations/Properties/AssemblyInfo.cs
cds/webapi/C#/CDSWebApiService/ParallelOperations/README.md
cds/webapi/C#/CDSWebApiService/ParallelOperations/packages.config

Adding initial samples using CDSWebApiService

Adding CDSWebApiService samples

---

cds/webapi/C#/CDSWebApiService/CDSWebApiService.sln
cds/webapi/C#/CDSWebApiService/QueryData/Program.cs
cds/webapi/C#/CDSWebApiService/QueryData/Properties/AssemblyInfo.cs
cds/webapi/C#/CDSWebApiService/QueryData/QueryData.csproj
cds/webapi/C#/CDSWebApiService/QueryData/README.md
cds/webapi/C#/CDSWebApiService/QueryData/packages.config

Included new example showing aggregation and nested $expand.

Adding Query Data sample

---

component-framework/TS_ReactStandardControl/ReactStandardControl/Facepile.tsx

Removed react version information from sample output

Remove react version display

---

ai-builder/README.md

For Brazilian e commerce dataset

Add data source citations

---

cds/webapi/C#/BasicOperations/Program.cs

The sample did not cleanup all of the data it added.

Cleanup contact2 (that was created via account2)

---

cds/webapi/C#/AsyncParallelOperations/AsyncParallelOperations.csproj
cds/webapi/C#/AsyncParallelOperations/Program.cs
cds/webapi/C#/AsyncParallelOperations/packages.config
cds/webapi/C#/BasicOperations/Program.cs
cds/webapi/C#/CDSWebApiService/CDSWebApiService.cs
cds/webapi/C#/CDSWebApiService/Extensions.cs
cds/webapi/C#/ConditionalOperations/Program.cs
cds/webapi/C#/FunctionAndActions/Program.cs
cds/webapi/C#/ParallelOperations/Program.cs
cds/webapi/C#/QueryData/Program.cs

- Changed all use of .Result to .GetAwaiter().GetResult() so that AggregateExceptions will not be returned
- Changed Uri parameter to string for Delete,Put,Patch methods for greater flexibility
- Changed body input parameter from JObject to object for greater flexibility with strong types
- Added 8 new methods that will be used in a metadata sample I will publish next
- Added comments for all methods
- Tested all current Web API samples and made adjustments for the changes above.

Refactor of CDSWebApiService

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1
powershell/admin-center/RunSamples.ps1

Add ReplacePolicyEnvironmentsForOnlyEnvironmentType function. It replaces policy environments with Teams environment for OnlyEnvironment type.

Add ReplacePolicyEnvironmentsForOnlyEnvironmentType

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1
powershell/admin-center/RunSamples.ps1

1. Replace the connector data to customer connector data in OldAPIToNewAPICompatibilityTests
2. Add Teams SKU filter in ReplacePolicyEnvironmentsForOnlyEnvironmentType

Replace customer connector data and Teams filter in ReplacePolicyEnvironmentsForOnlyEnvironmentType

---

cds/orgsvc/C#/AuditEntityData/AuditEntityData/SampleMethod.cs
cds/orgsvc/C#/AuditEntityData/AuditEntityData/SampleProgram.cs

Thought I'd tidy up a bit since I was here
- Using Update correctly
- Modernize the programming style

Cleaning up the sample

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1
powershell/admin-center/RunSamples.ps1

By Geoffrey Guo <geoffguo@microsoft.com>

PowerShell samples update

---

cds/App.config
cds/orgsvc/C#/DiscoveryService/DiscoveryService.csproj
cds/orgsvc/C#/DiscoveryService/SampleMethods.cs
cds/orgsvc/C#/DiscoveryService/SampleProgram.cs
cds/orgsvc/C#/DiscoveryService/packages.config

Updated the Discovery Sample to work post the deprecation of the Regional Discovery Servers.

Updated for Global Discovery Use.

---

cds/Xrm Tooling/Quick start for XRM Tooling API/C#/QuickStartXRMToolingWPFClient/LoginWindow/CrmLogin.xaml.cs

Update default login control demo to use oAuth.

Update Login control demo to enabled OAuth by default.

---

ai-builder/labs/README.md

to include latest lab package.

Updating readme

---

cds/orgsvc/C#/UseFetchXMLWithPaging/UseFetchXMLWithPaging/SampleMethod.cs
cds/orgsvc/C#/UseFetchXMLWithPaging/UseFetchXMLWithPaging/SampleProgram.cs

Moved the CreateXml function from SampleMethods to SampleProgram.

Addressing feedback item 3201

---

cds/orgsvc/C#/QueriesUsingLINQ/ComplexQueries/App.config
cds/orgsvc/C#/QueriesUsingLINQ/ComplexQueries/ComplexQueries.csproj
cds/orgsvc/C#/QueriesUsingLINQ/ComplexQueries/packages.config
cds/orgsvc/C#/QueriesUsingLINQ/CreateQuery/App.config
cds/orgsvc/C#/QueriesUsingLINQ/CreateQuery/Create a LINQ query.csproj
cds/orgsvc/C#/QueriesUsingLINQ/CreateQuery/packages.config
cds/orgsvc/C#/QueriesUsingLINQ/LateBoundQuery/App.config
cds/orgsvc/C#/QueriesUsingLINQ/LateBoundQuery/Query using late binding.csproj
cds/orgsvc/C#/QueriesUsingLINQ/LateBoundQuery/packages.config
cds/orgsvc/C#/QueriesUsingLINQ/QueriesUsingLINQ/Shared library.csproj
cds/orgsvc/C#/QueriesUsingLINQ/QueriesUsingLINQ/app.config
cds/orgsvc/C#/QueriesUsingLINQ/QueriesUsingLINQ/packages.config
cds/orgsvc/C#/QueriesUsingLINQ/RetrieveMultipleUsingConditions/App.config
cds/orgsvc/C#/QueriesUsingLINQ/RetrieveMultipleUsingConditions/Retrieve multiple using conditions.csproj
cds/orgsvc/C#/QueriesUsingLINQ/RetrieveMultipleUsingConditions/packages.config

Added reference to Microsoft.CrmSdk.XrmTooling.WpfControls

Fix ComplexQueries project

---

cds/orgsvc/C#-NETCore/ServiceClient/CreateUpdateDelete/CreateUpdateDelete.csproj
cds/orgsvc/C#-NETCore/ServiceClient/CreateUpdateDelete/Program.cs
cds/orgsvc/C#-NETCore/ServiceClient/README.md
cds/orgsvc/C#-NETCore/ServiceClient/ServiceClient.sln
cds/orgsvc/C#-NETCore/ServiceClient/TelemetryUsingILogger/Program.cs
cds/orgsvc/C#-NETCore/ServiceClient/TelemetryUsingILogger/TelemetryUsingILogger.csproj
cds/orgsvc/C#-NETCore/ServiceClient/WhoAmI/Program.cs
cds/orgsvc/C#-NETCore/ServiceClient/WhoAmI/WhoAmI.csproj
cds/orgsvc/C#-NETCore/ServiceClient/appsettings.json

New ServiceClient examples based on .NET 6 and MSAL authentication.

Dataverse sdk samples

---

cds/App.config
cds/GenerateEntityDiagram/GenerateEntityDiagram/App.config
cds/GenerateEntityDiagram/GenerateEntityDiagram/GenerateEntityDiagram.csproj
cds/GenerateEntityDiagram/GenerateEntityDiagram/packages.config
cds/GenerateEntityDiagram/README.md
cds/online-management-api/RetrieveInstances/App.config
cds/online-management-api/RetrieveInstances/SampleAppForOnlineAdminAPI.csproj
cds/online-management-api/RetrieveInstances/packages.config
cds/orgsvc/C#/SendEmailUsingTemp/SendEmailUsingTemp/SendEmailUsingTemp.csproj
cds/orgsvc/C#/SendEmailUsingTemp/SendEmailUsingTemp/packages.config

NuGet package updated

---

ai-builder/BringYourOwnModelTutorial/PneumoniaDetection/model/myenv.yml

Pinning sample endpoint ACI environment requirements to specific package versions

Pinning BYOM sample endpoint environment requirements

---

dataverse/orgsvc/C#/GoalDataForFiscalYear/README.md
dataverse/orgsvc/C#/QueriesTrackGoals/README.md
dataverse/orgsvc/C#/RollupGoalData/README.md
dataverse/orgsvc/C#/ShareRecordUsingAccessTeam/README.md

About required system user accounts

Updated README with more info

---

dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/ConsoleApp.csproj
dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/ConsoleApp.sln
dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/Program.cs
dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/README.md

Related to topic [Quickstart: Execute an Organization service request](https://learn.microsoft.com/power-apps/developer/data-platform/org-service/quick-start-org-service-console-app)

New get started sample

---

dataverse/orgsvc/C#-NETCore/Schema/README.md
dataverse/orgsvc/C#-NETCore/Schema/RetrieveMetadataChanges/Program.cs
dataverse/orgsvc/C#-NETCore/Schema/RetrieveMetadataChanges/RetrieveMetadataChanges.csproj
dataverse/orgsvc/C#-NETCore/Schema/Schema.sln
dataverse/orgsvc/C#-NETCore/Schema/appsettings.json
dataverse/webapi/C#-NETx/RetrieveMetadataChanges/Program.cs
dataverse/webapi/C#-NETx/RetrieveMetadataChanges/README.md
dataverse/webapi/C#-NETx/RetrieveMetadataChanges/RetrieveMetadataChanges.csproj
dataverse/webapi/C#-NETx/RetrieveMetadataChanges/RetrieveMetadataChanges.sln
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Messages/CreateAttributeRequest.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Messages/DeleteAttributeRequest.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Messages/RetrieveMetadataChangesRequest.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Messages/RetrieveMetadataChangesResponse.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Messages/SetLocLabelsRequest.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/AttributeQueryExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/ComplexEntityMetadata.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/DeletedMetadataCollection.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/DeletedMetadataFilters.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/EntityKeyQueryExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/EntityQueryExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/GuidCollection.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/LabelQueryExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/LogicalOperator.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/MetadataConditionExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/MetadataConditionOperator.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/MetadataFilterExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/MetadataPropertiesExpression.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/Object.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/ObjectType.cs
dataverse/webapi/C#-NETx/WebAPIService/Metadata/Types/RelationshipQueryExpression.cs

An SDK sample and one using Web API

Adding RetrieveMetadataChanges samples

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1

4 public functions are added:
1. Enable Managment for a given environment
2. Disable Management for a given environment
3. Include insights for a given managed environment in weekly email digest
3. Exclude insights for a given managed environment in weekly email digest

Add helper functions for Managed Environments

---

component-framework/ChoicesPickerControl/ChoicesPicker/index.ts

The 'configuration' has been repeated in the if block's condition.

Removed duplicated condition from if block

---

dataverse/App.config
dataverse/Xrm Tooling/Quick start for XRM Tooling API/C#/QuickStartXRMToolingWPFClient/App.config
dataverse/Xrm Tooling/Quick start for XRM Tooling API/C#/QuickStartXRMToolingWPFClient/Properties/Resources.Designer.cs
dataverse/Xrm Tooling/Quick start for XRM Tooling API/C#/QuickStartXRMToolingWPFClient/Properties/Settings.Designer.cs
dataverse/Xrm Tooling/Quick start for XRM Tooling API/C#/QuickStartXRMToolingWPFClient/QuickStartXRMToolingWPFClient.csproj
dataverse/Xrm Tooling/Quick start for XRM Tooling API/C#/QuickStartXRMToolingWPFClient/packages.config
dataverse/Xrm Tooling/QuickStartCS/QuickStartCS/QuickStartCS.csproj
dataverse/Xrm Tooling/QuickStartCS/QuickStartCS/packages.config
dataverse/Xrm Tooling/TPLCrmServiceClient/TPLCrmServiceClient.csproj
dataverse/Xrm Tooling/TPLCrmServiceClient/packages.config

Updated NuGet packages to latest versions and .NET Framework to v4.8

Updated to .NET v4.8

---

dataverse/orgsvc/C#-NETCore/AttachmentAndAnnotationOperations/ActivityMimeAttachmentOperations/Program.cs
dataverse/orgsvc/C#-NETCore/AttachmentAndAnnotationOperations/AnnotationOperations/Program.cs
dataverse/orgsvc/C#-NETCore/FileOperations/Program.cs
dataverse/orgsvc/C#-NETCore/ImageOperations/Program.cs
dataverse/webapi/C#-NETx/AttachmentAndAnnotationOperations/ActivityMimeAttachmentOperations/Program.cs
dataverse/webapi/C#-NETx/AttachmentAndAnnotationOperations/AnnotationOperations/Program.cs
dataverse/webapi/C#-NETx/FileOperations/FileOperationsWithActions/Program.cs
dataverse/webapi/C#-NETx/ImageOperations/Program.cs

Apply changes from code review

Changes from code review

---

component-framework/FormattingAPIControl/FormattingAPIControl/ControlManifest.Input.xml
component-framework/FormattingAPIControl/FormattingAPIControl/index.ts

I think this example is a little more helpful when it is working properly 😸

updated FormattingAPIControl to use the parameters

---

powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/ConnectionHelper.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/EnvironmentOperationsHelper.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/Logger.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Powershell/Microsoft.PowerPlatform.Administration.UserManagement.psm1

Adding accurate geo codes, minor logging fixes

Adding accurate geo codes, minor logging fixes

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1

Add function 
1. SetManagedEnvironmentMakerOnboardingMarkdownContents : for setting maker onboarding contents
2. SetManagedEnvironmentMakerOnboardingLearnMoreUrl : for maker onboarding learn more url

Add Managed Governance Maker Onboarding functions

---

dataverse/webapi/C#/SingleTenantS2S/Program.cs
dataverse/webapi/C#/SingleTenantS2S/README.md

S2S sample update

---

dataverse/webapi/C#/SingleTenantS2S/App.config
dataverse/webapi/C#/SingleTenantS2S/README.md

Updated the App.config file and README

Minor updates

---

powershell/enterprisePolicies/SetupSubscriptionForPowerPlatform.ps1
powershell/enterprisePolicies/SubnetInjection/SetupVnetForSubnetDelegation.ps1

The code in this PR:
- fixes the enterprise policy script to stop execution when error is encountered

Update Enterprise Policy sample script to stop execution in case of error

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1

Add validation on settings being available before setting the value

---

dataverse/webapi/C#-NETx/ElasticTableOperations/Program.cs
dataverse/webapi/C#-NETx/ElasticTableOperations/README.md
dataverse/webapi/C#-NETx/WebAPIService/Messages/DeleteMultipleRequest.cs

- CreateMultiple
- UpdateMultiple
- DeleteMultiple

Update to demonstrate use of:

---

dataverse/orgsvc/C#-NETCore/ElasticTableOperations/ElasticTableOperations.csproj
dataverse/orgsvc/C#-NETCore/ElasticTableOperations/README.md
dataverse/orgsvc/C#-NETCore/ElasticTableOperations/Utility.cs

with CreateEntityRequest rather than Web API.

Updating code to use EntityMetadata.TableType property 

---

dataverse/webapi/C#-NETx/FunctionsAndActions/README.md

Updating reference links in [Web API Functions and Actions sample - Code Samples | Microsoft Learn](https://learn.microsoft.com/en-us/samples/microsoft/powerapps-samples/web-api-functions-and-actions-sample/):
Replacing github relative links with absolute links.

Kbond fns acts link update 8 sep23

---

powershell/connectors/HTTPWithMicrosoftEntraId/ManagePermissionGrant.ps1
powershell/connectors/HTTPWithMicrosoftEntraId/README.md

Adding a grant management script for connector: "HTTP with Microsoft Entra ID"

HTTP with Microsoft Entra ID - Add grant management script

---

dataverse/webapi/C#-NETx/QuickStart/Program.cs
dataverse/webapi/C#/EnhancedQuickStart/OAuthMessageHandler.cs
dataverse/webapi/C#/QuickStart/QuickStartMSAL/Program.cs

For public clients, the scope should be <env-url>/user_impersonation

Changed authentication scope

---

dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/ConsoleApp.csproj
dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/Program.cs
dataverse/orgsvc/C#-NETCore/GetStarted/quickstart-execute-request/README.md

Simplify the quick start to highlight use of IOrganizationService

Jdaly master quickstart

---

dataverse/orgsvc/C#-NETCore/BulkOperations/CreateUpdateMultiple/CreateUpdateMultiple.csproj
dataverse/orgsvc/C#-NETCore/BulkOperations/ExecuteMultiple/ExecuteMultiple.csproj
dataverse/orgsvc/C#-NETCore/BulkOperations/ParallelCreateUpdateMultiple/ParallelCreateUpdateMultiple.csproj
dataverse/orgsvc/C#-NETCore/BulkOperations/README.md
dataverse/orgsvc/C#-NETCore/BulkOperations/Settings.cs
dataverse/orgsvc/C#-NETCore/BulkOperations/SimpleLoop/SimpleLoop.csproj
dataverse/orgsvc/C#-NETCore/BulkOperations/UpsertMultiple/Program.cs
dataverse/orgsvc/C#-NETCore/BulkOperations/UpsertMultiple/README.md
dataverse/orgsvc/C#-NETCore/BulkOperations/UpsertMultiple/UpsertMultiple.csproj
dataverse/orgsvc/C#-NETCore/BulkOperations/Utility.cs
dataverse/orgsvc/C#-NETCore/BulkOperations/xMultipleSamples.sln

Also updates to some of the other Bulk Operation projects

Add UpsertMultiple sample

---

powershell/connectors/HTTPWithMicrosoftEntraId/ManagePermissionGrant.ps1

If service principal is not present in the tenant create a new one.

Create a SP if not present

---

powershell/connectors/HTTPWithMicrosoftEntraId/ManagePermissionGrant.ps1

ManagerPermissionGrant broken

---

powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/EnvironmentOperationsHelper.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/Logger.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/RoleManagementOperationsHelper.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/TenantOperationsHelper.cs
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Powershell/Microsoft.PowerPlatform.Administration.UserManagement.psm1
powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/README.md

Add bulk assignment of records ps script to enable cx to perform bulk assignment of user records.

add bulk assignment of records to UserManagement powershell script

---

component-framework/AngularJSFlipControl/README.md
component-framework/AngularJSFlipControl/assets/sample.json

**Goal**: Make the samples discoverable here:
A.	[Browse code samples | Microsoft Learn](https://learn.microsoft.com/en-us/samples/browse/?expanded=power-platform&products=power-apps) (Microsoft Learn Sample Browser)
B.	[Sample Solution Gallery - Microsoft Adoption](https://adoption.microsoft.com/en-us/sample-solution-gallery/?keyword=&sort-by=&page=1&product=Power+Apps) (Microsoft Adoption Sample Solution Gallery)

Adding README and sample.json files for discovery

---

powershell/UserManagement/Microsoft.PowerPlatform.Administration.UserManagement/Microsoft.PowerPlatform.Administration.Helpers/RoleManagementOperationsHelper.cs

Update logging in RoleManagementOperationsHelper.cs

Update logging in RoleManagementOperationsHelper.cs

---

dataverse/App.config
dataverse/orgsvc/C#/CRUDEmailAttachments/CRUDEmailAttachments/App.config
dataverse/orgsvc/C#/CRUDEmailAttachments/CRUDEmailAttachments/CRUDEmailAttachments.csproj
dataverse/orgsvc/C#/CRUDEmailAttachments/CRUDEmailAttachments/packages.config
dataverse/orgsvc/C#/CRUDOperationsChart/CRUDOperationsChart/App.config
dataverse/orgsvc/C#/CRUDOperationsChart/CRUDOperationsChart/CRUDOperationsChart.csproj
dataverse/orgsvc/C#/CRUDOperationsChart/CRUDOperationsChart/packages.config
dataverse/orgsvc/C#/ConnectionEarlyBound/Connection(Early Bound)/ConnectionEarlyBound.csproj
dataverse/orgsvc/C#/ConnectionEarlyBound/Connection(Early Bound)/packages.config

Updated NuGet packages in a few samples

---

dataverse/GenerateEntityDiagram/GenerateEntityDiagram/GenerateEntityDiagram.sln
dataverse/GenerateEntityDiagram/GenerateEntityDiagram/Helper-Code/SampleHelpers.cs

Fixed connection string bug

---

powershell/admin-center/Microsoft.PowerApps.Administration.PowerShell.Samples.psm1

Add RuleOverrides parameter to SetManagedEnvironmentSolutionCheckerEnforcementLevel in response to latest post at https://community.powerplatform.com/forums/thread/details/?threadid=e44b1446-e150-4337-96fe-fc4e06610f2f

Add RuleOverrides parameter to SetManagedEnvironmentSolutionCheckerEnforcementLevel

---

dataverse/orgsvc/CSharp-NETCore/Relationships/AssociateDisassociate/Program.cs

Testing the code injection feature of our publishing system.

Added snippet tags

---

dataverse/webapi/CSharp-NETx/AttachmentAndAnnotationOperations/ActivityMimeAttachmentOperations/ActivityMimeAttachmentOperations.csproj
dataverse/webapi/CSharp-NETx/AttachmentAndAnnotationOperations/AnnotationOperations/AnnotationOperations.csproj
dataverse/webapi/CSharp-NETx/BasicOperations/BasicOperations.csproj
dataverse/webapi/CSharp-NETx/BulkOperations/CreateUpdateMultiple/CreateUpdateMultiple.csproj
dataverse/webapi/CSharp-NETx/BulkOperations/ParallelCreateUpdateMultiple/ParallelCreateUpdateMultiple.csproj
dataverse/webapi/CSharp-NETx/BulkOperations/UpsertMultiple/UpsertMultiple.csproj
dataverse/webapi/CSharp-NETx/ConditionalOperations/ConditionalOperations.csproj
dataverse/webapi/CSharp-NETx/FileOperations/FileOperationsWithActions/FileOperationsWithActions.csproj
dataverse/webapi/CSharp-NETx/FunctionsAndActions/FunctionsAndActions.csproj
dataverse/webapi/CSharp-NETx/ImageOperations/ImageOperations.csproj
dataverse/webapi/CSharp-NETx/MetadataOperations/MetadataOperations.csproj
dataverse/webapi/CSharp-NETx/ParallelOperations/ParallelOperations.csproj
dataverse/webapi/CSharp-NETx/QueryData/QueryData.csproj
dataverse/webapi/CSharp-NETx/QuickStart/QuickStart.csproj
dataverse/webapi/CSharp-NETx/RetrieveMetadataChanges/RetrieveMetadataChanges.csproj
dataverse/webapi/CSharp-NETx/Search/Search.csproj
dataverse/webapi/CSharp-NETx/TPLDataFlowParallelOperations/TPLDataFlowParallelOperations.csproj

Updating for all samples that use the Web API Service

Update Nuget Packages for Web API samples

---

powershell/enterprisePolicies/README.md

Updating README to include more information (ex. how to delete EP), fixing formatting, links to files, etc.

Updating EnterprisePolicies README (particularly for Subnet Injection)

---

powershell/enterprisePolicies/Common/EnvironmentEnterprisePolicyOperations.ps1
powershell/enterprisePolicies/README.md

* Update EnvironmentEnterprisePolicyOperations.ps1 to be case insensitive when comparing enterprise policy id
* Adding to FAQ for case when user gets "environment not found" when missing permissions

Update EnvironmentEnterprisePolicyOperations.ps1 to be case insensitive, Update README (EnterprisePolicies FAQ)

---

portals/PortalWebAPIControl/package-lock.json

There have been so many dependabot updates that the package-lock.json file has more than 100 conflicts.
Just regenerating a new one.

regen package lock file
